<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> page deleting' => '<strong>Conferma</strong> l\'eliminazione della pagina',
    '<strong>Confirm</strong> page reverting' => '<strong>Conferma</strong> il recupero della pagina',
    '<strong>Overview</strong> of all pages' => '<strong>Panoramica</strong> di tutte le pagine',
    '<strong>Page</strong> history' => '<strong>Storico</strong> pagina',
    '<strong>Wiki</strong> Module' => '<strong>Wiki</strong>',
    'Adds a wiki to this space.' => 'Aggiungi wiki a questa pagina',
    'Adds a wiki to your profile.' => 'Aggiungi wiki al tuo profilo',
    'Back to page' => 'Torna indietro',
    'Do you really want to delete this page?' => 'Sei sicuro di voler eliminare questa pagina?',
    'Do you really want to revert this page?' => 'Sei sicuro di voler recuperare questa pagina?',
    'Edit page' => 'Modifica pagina',
    'Edited at' => 'A cura di',
    'Go back' => 'Torna indietro',
    'Invalid character in page title!' => 'Corattere non valido nel titolo della pagina!',
    'Let\'s go!' => 'Andiamo!',
    'Main page' => 'Pagina principale',
    'New page' => 'Nuova pagina',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => 'Non ci sono pagine create. Inizia tu creando una pagina!',
    'Overview' => 'Panoramica',
    'Page History' => 'Storico pagina',
    'Page title already in use!' => 'Titolo di pagina già in uso!',
    'Permalink' => 'Link permanente',
    'Revert' => 'Ripristina',
    'Revert this' => 'Ripristina questo',
    'View' => 'Vedi',
    'Wiki' => 'Wiki',
    'by' => 'di',
    'Cancel' => 'Annulla',
    'Delete' => 'Cancella',
];
